# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/optimizer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/optimizer.proto',
  package='',
  syntax='proto2',
  serialized_pb=b'\n\x16protos/optimizer.proto\"\x84\x01\n\tOptimizer\x12$\n\x07\x61\x64\x61grad\x18\x01 \x01(\x0b\x32\x11.AdagradOptimizerH\x00\x12$\n\x07rmsprop\x18\x02 \x01(\x0b\x32\x11.RMSPropOptimizerH\x00\x12\x1e\n\x04\x61\x64\x61m\x18\x03 \x01(\x0b\x32\x0e.AdamOptimizerH\x00\x42\x0b\n\toptimizer\":\n\x10\x41\x64\x61gradOptimizer\x12&\n\x19initial_accumulator_value\x18\x01 \x01(\x02:\x03\x30.1\"l\n\x10RMSPropOptimizer\x12\x12\n\x05\x64\x65\x63\x61y\x18\x01 \x01(\x02:\x03\x30.9\x12\x13\n\x08momentum\x18\x02 \x01(\x02:\x01\x30\x12\x16\n\x07\x65psilon\x18\x03 \x01(\x02:\x05\x31\x65-07\x12\x17\n\x08\x63\x65ntered\x18\x04 \x01(\x08:\x05\x66\x61lse\"Q\n\rAdamOptimizer\x12\x12\n\x05\x62\x65ta1\x18\x01 \x01(\x02:\x03\x30.9\x12\x14\n\x05\x62\x65ta2\x18\x02 \x01(\x02:\x05\x30.999\x12\x16\n\x07\x65psilon\x18\x03 \x01(\x02:\x05\x31\x65-07'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OPTIMIZER = _descriptor.Descriptor(
  name='Optimizer',
  full_name='Optimizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adagrad', full_name='Optimizer.adagrad', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rmsprop', full_name='Optimizer.rmsprop', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adam', full_name='Optimizer.adam', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optimizer', full_name='Optimizer.optimizer',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=27,
  serialized_end=159,
)


_ADAGRADOPTIMIZER = _descriptor.Descriptor(
  name='AdagradOptimizer',
  full_name='AdagradOptimizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initial_accumulator_value', full_name='AdagradOptimizer.initial_accumulator_value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=219,
)


_RMSPROPOPTIMIZER = _descriptor.Descriptor(
  name='RMSPropOptimizer',
  full_name='RMSPropOptimizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decay', full_name='RMSPropOptimizer.decay', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.9,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='momentum', full_name='RMSPropOptimizer.momentum', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='RMSPropOptimizer.epsilon', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1e-07,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='centered', full_name='RMSPropOptimizer.centered', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=329,
)


_ADAMOPTIMIZER = _descriptor.Descriptor(
  name='AdamOptimizer',
  full_name='AdamOptimizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beta1', full_name='AdamOptimizer.beta1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.9,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta2', full_name='AdamOptimizer.beta2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.999,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='AdamOptimizer.epsilon', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1e-07,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=412,
)

_OPTIMIZER.fields_by_name['adagrad'].message_type = _ADAGRADOPTIMIZER
_OPTIMIZER.fields_by_name['rmsprop'].message_type = _RMSPROPOPTIMIZER
_OPTIMIZER.fields_by_name['adam'].message_type = _ADAMOPTIMIZER
_OPTIMIZER.oneofs_by_name['optimizer'].fields.append(
  _OPTIMIZER.fields_by_name['adagrad'])
_OPTIMIZER.fields_by_name['adagrad'].containing_oneof = _OPTIMIZER.oneofs_by_name['optimizer']
_OPTIMIZER.oneofs_by_name['optimizer'].fields.append(
  _OPTIMIZER.fields_by_name['rmsprop'])
_OPTIMIZER.fields_by_name['rmsprop'].containing_oneof = _OPTIMIZER.oneofs_by_name['optimizer']
_OPTIMIZER.oneofs_by_name['optimizer'].fields.append(
  _OPTIMIZER.fields_by_name['adam'])
_OPTIMIZER.fields_by_name['adam'].containing_oneof = _OPTIMIZER.oneofs_by_name['optimizer']
DESCRIPTOR.message_types_by_name['Optimizer'] = _OPTIMIZER
DESCRIPTOR.message_types_by_name['AdagradOptimizer'] = _ADAGRADOPTIMIZER
DESCRIPTOR.message_types_by_name['RMSPropOptimizer'] = _RMSPROPOPTIMIZER
DESCRIPTOR.message_types_by_name['AdamOptimizer'] = _ADAMOPTIMIZER

Optimizer = _reflection.GeneratedProtocolMessageType('Optimizer', (_message.Message,), dict(
  DESCRIPTOR = _OPTIMIZER,
  __module__ = 'protos.optimizer_pb2'
  # @@protoc_insertion_point(class_scope:Optimizer)
  ))
_sym_db.RegisterMessage(Optimizer)

AdagradOptimizer = _reflection.GeneratedProtocolMessageType('AdagradOptimizer', (_message.Message,), dict(
  DESCRIPTOR = _ADAGRADOPTIMIZER,
  __module__ = 'protos.optimizer_pb2'
  # @@protoc_insertion_point(class_scope:AdagradOptimizer)
  ))
_sym_db.RegisterMessage(AdagradOptimizer)

RMSPropOptimizer = _reflection.GeneratedProtocolMessageType('RMSPropOptimizer', (_message.Message,), dict(
  DESCRIPTOR = _RMSPROPOPTIMIZER,
  __module__ = 'protos.optimizer_pb2'
  # @@protoc_insertion_point(class_scope:RMSPropOptimizer)
  ))
_sym_db.RegisterMessage(RMSPropOptimizer)

AdamOptimizer = _reflection.GeneratedProtocolMessageType('AdamOptimizer', (_message.Message,), dict(
  DESCRIPTOR = _ADAMOPTIMIZER,
  __module__ = 'protos.optimizer_pb2'
  # @@protoc_insertion_point(class_scope:AdamOptimizer)
  ))
_sym_db.RegisterMessage(AdamOptimizer)


# @@protoc_insertion_point(module_scope)
