# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pipeline.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import model_pb2 as protos_dot_model__pb2
from protos import optimizer_pb2 as protos_dot_optimizer__pb2
from protos import learning_rate_schedule_pb2 as protos_dot_learning__rate__schedule__pb2
from protos import reader_pb2 as protos_dot_reader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/pipeline.proto',
  package='',
  syntax='proto2',
  serialized_pb=b'\n\x15protos/pipeline.proto\x1a\x12protos/model.proto\x1a\x16protos/optimizer.proto\x1a#protos/learning_rate_schedule.proto\x1a\x13protos/reader.proto\"\xa4\x01\n\x08Pipeline\x12\x1d\n\x0ctrain_reader\x18\x01 \x01(\x0b\x32\x07.Reader\x12\x1c\n\x0b\x65val_reader\x18\x02 \x01(\x0b\x32\x07.Reader\x12\x15\n\x05model\x18\x03 \x01(\x0b\x32\x06.Model\x12\"\n\x0ctrain_config\x18\x04 \x01(\x0b\x32\x0c.TrainConfig\x12 \n\x0b\x65val_config\x18\x05 \x01(\x0b\x32\x0b.EvalConfig\"T\n\nEvalConfig\x12\r\n\x05steps\x18\x01 \x01(\r\x12\x1c\n\x10start_delay_secs\x18\x02 \x01(\r:\x02\x36\x30\x12\x19\n\rthrottle_secs\x18\x03 \x01(\r:\x02\x36\x30\"\x9d\x02\n\x0bTrainConfig\x12\x35\n\x16learning_rate_schedule\x18\x01 \x01(\x0b\x32\x15.LearningRateSchedule\x12\x1d\n\toptimizer\x18\x02 \x01(\x0b\x32\n.Optimizer\x12\x11\n\tmax_steps\x18\x03 \x01(\r\x12\"\n\x14log_step_count_steps\x18\x04 \x01(\x05:\x04\x32\x30\x30\x30\x12 \n\x12save_summary_steps\x18\x05 \x01(\r:\x04\x32\x30\x30\x30\x12$\n\x16save_checkpoints_steps\x18\x06 \x01(\r:\x04\x32\x30\x30\x30\x12\x1e\n\x13keep_checkpoint_max\x18\x07 \x01(\r:\x01\x35\x12\x19\n\x11max_gradient_norm\x18\x08 \x01(\x02'
  ,
  dependencies=[protos_dot_model__pb2.DESCRIPTOR,protos_dot_optimizer__pb2.DESCRIPTOR,protos_dot_learning__rate__schedule__pb2.DESCRIPTOR,protos_dot_reader__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PIPELINE = _descriptor.Descriptor(
  name='Pipeline',
  full_name='Pipeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_reader', full_name='Pipeline.train_reader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_reader', full_name='Pipeline.eval_reader', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='Pipeline.model', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='Pipeline.train_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_config', full_name='Pipeline.eval_config', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=292,
)


_EVALCONFIG = _descriptor.Descriptor(
  name='EvalConfig',
  full_name='EvalConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steps', full_name='EvalConfig.steps', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_delay_secs', full_name='EvalConfig.start_delay_secs', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=60,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='throttle_secs', full_name='EvalConfig.throttle_secs', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=60,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=378,
)


_TRAINCONFIG = _descriptor.Descriptor(
  name='TrainConfig',
  full_name='TrainConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='learning_rate_schedule', full_name='TrainConfig.learning_rate_schedule', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optimizer', full_name='TrainConfig.optimizer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_steps', full_name='TrainConfig.max_steps', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_step_count_steps', full_name='TrainConfig.log_step_count_steps', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_summary_steps', full_name='TrainConfig.save_summary_steps', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=2000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save_checkpoints_steps', full_name='TrainConfig.save_checkpoints_steps', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=2000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keep_checkpoint_max', full_name='TrainConfig.keep_checkpoint_max', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_gradient_norm', full_name='TrainConfig.max_gradient_norm', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=666,
)

_PIPELINE.fields_by_name['train_reader'].message_type = protos_dot_reader__pb2._READER
_PIPELINE.fields_by_name['eval_reader'].message_type = protos_dot_reader__pb2._READER
_PIPELINE.fields_by_name['model'].message_type = protos_dot_model__pb2._MODEL
_PIPELINE.fields_by_name['train_config'].message_type = _TRAINCONFIG
_PIPELINE.fields_by_name['eval_config'].message_type = _EVALCONFIG
_TRAINCONFIG.fields_by_name['learning_rate_schedule'].message_type = protos_dot_learning__rate__schedule__pb2._LEARNINGRATESCHEDULE
_TRAINCONFIG.fields_by_name['optimizer'].message_type = protos_dot_optimizer__pb2._OPTIMIZER
DESCRIPTOR.message_types_by_name['Pipeline'] = _PIPELINE
DESCRIPTOR.message_types_by_name['EvalConfig'] = _EVALCONFIG
DESCRIPTOR.message_types_by_name['TrainConfig'] = _TRAINCONFIG

Pipeline = _reflection.GeneratedProtocolMessageType('Pipeline', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINE,
  __module__ = 'protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:Pipeline)
  ))
_sym_db.RegisterMessage(Pipeline)

EvalConfig = _reflection.GeneratedProtocolMessageType('EvalConfig', (_message.Message,), dict(
  DESCRIPTOR = _EVALCONFIG,
  __module__ = 'protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:EvalConfig)
  ))
_sym_db.RegisterMessage(EvalConfig)

TrainConfig = _reflection.GeneratedProtocolMessageType('TrainConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAINCONFIG,
  __module__ = 'protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:TrainConfig)
  ))
_sym_db.RegisterMessage(TrainConfig)


# @@protoc_insertion_point(module_scope)
