# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/rcnn.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/rcnn.proto',
  package='',
  syntax='proto2',
  serialized_pb=b'\n\x11protos/rcnn.proto\"\xbe\x01\n\x04RCNN\x12,\n\x16\x66\x65\x61ture_extractor_name\x18\x01 \x01(\t:\x0cinception_v4\x12,\n\x17\x66\x65\x61ture_extractor_scope\x18\x02 \x01(\t:\x0bInceptionV4\x12\x34\n\x1a\x66\x65\x61ture_extractor_endpoint\x18\x03 \x01(\t:\x10PreLogitsFlatten\x12$\n\x1c\x66\x65\x61ture_extractor_checkpoint\x18\x04 \x01(\t'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RCNN = _descriptor.Descriptor(
  name='RCNN',
  full_name='RCNN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_extractor_name', full_name='RCNN.feature_extractor_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"inception_v4".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_extractor_scope', full_name='RCNN.feature_extractor_scope', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"InceptionV4".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_extractor_endpoint', full_name='RCNN.feature_extractor_endpoint', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"PreLogitsFlatten".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_extractor_checkpoint', full_name='RCNN.feature_extractor_checkpoint', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['RCNN'] = _RCNN

RCNN = _reflection.GeneratedProtocolMessageType('RCNN', (_message.Message,), dict(
  DESCRIPTOR = _RCNN,
  __module__ = 'protos.rcnn_pb2'
  # @@protoc_insertion_point(class_scope:RCNN)
  ))
_sym_db.RegisterMessage(RCNN)


# @@protoc_insertion_point(module_scope)
