# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/rnn.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import hyperparams_pb2 as protos_dot_hyperparams__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/rnn.proto',
  package='',
  syntax='proto2',
  serialized_pb=b'\n\x10protos/rnn.proto\x1a\x18protos/hyperparams.proto\"-\n\x03RNN\x12\x19\n\x06\x62ilstm\x18\x03 \x01(\x0b\x32\x07.BiLSTMH\x00\x42\x0b\n\trnn_oneof\"\x95\x01\n\x06\x42iLSTM\x12\x1b\n\x10number_of_layers\x18\x01 \x01(\x05:\x01\x31\x12\x19\n\x0chidden_units\x18\x02 \x01(\x05:\x03\x33\x30\x30\x12\x1a\n\x0finput_keep_prob\x18\x03 \x01(\x02:\x01\x31\x12\x1b\n\x10output_keep_prob\x18\x04 \x01(\x02:\x01\x31\x12\x1a\n\x0fstate_keep_prob\x18\x05 \x01(\x02:\x01\x31'
  ,
  dependencies=[protos_dot_hyperparams__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RNN = _descriptor.Descriptor(
  name='RNN',
  full_name='RNN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bilstm', full_name='RNN.bilstm', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='rnn_oneof', full_name='RNN.rnn_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=46,
  serialized_end=91,
)


_BILSTM = _descriptor.Descriptor(
  name='BiLSTM',
  full_name='BiLSTM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_layers', full_name='BiLSTM.number_of_layers', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden_units', full_name='BiLSTM.hidden_units', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=300,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_keep_prob', full_name='BiLSTM.input_keep_prob', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_keep_prob', full_name='BiLSTM.output_keep_prob', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_keep_prob', full_name='BiLSTM.state_keep_prob', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=243,
)

_RNN.fields_by_name['bilstm'].message_type = _BILSTM
_RNN.oneofs_by_name['rnn_oneof'].fields.append(
  _RNN.fields_by_name['bilstm'])
_RNN.fields_by_name['bilstm'].containing_oneof = _RNN.oneofs_by_name['rnn_oneof']
DESCRIPTOR.message_types_by_name['RNN'] = _RNN
DESCRIPTOR.message_types_by_name['BiLSTM'] = _BILSTM

RNN = _reflection.GeneratedProtocolMessageType('RNN', (_message.Message,), dict(
  DESCRIPTOR = _RNN,
  __module__ = 'protos.rnn_pb2'
  # @@protoc_insertion_point(class_scope:RNN)
  ))
_sym_db.RegisterMessage(RNN)

BiLSTM = _reflection.GeneratedProtocolMessageType('BiLSTM', (_message.Message,), dict(
  DESCRIPTOR = _BILSTM,
  __module__ = 'protos.rnn_pb2'
  # @@protoc_insertion_point(class_scope:BiLSTM)
  ))
_sym_db.RegisterMessage(BiLSTM)


# @@protoc_insertion_point(module_scope)
